print("-----------------------------------------------------------")
print("|                 ABSA BANK                               |")
print("|               MUTHAIGA BRANCH                           |")
print("|              8TH FEBRUARY 2023                          |")
print("|                                                         |")
print("|First name:Marie                                         |")
print("|Second name:Wairimu                                      |")
print("|Sirname:Wambui                                           |")
print("|ACC NUMBER:111730340130                                  |")
print("|ACC BALANCE:KSH 2,500,000                                |")
print("|                                                         |")
print("|             ABSA:COMMITED TO SERVE                      |")
print("|---------------------------------------------------------|")

