
print("=================")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("================")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print('=================================')
print('||   Miss Marie Limited        ||')
print('||     Better Together         ||')
print("||        Since 2004           ||")
print("================================")


