name = input("What is your first name?")
print("My name is",name)
f_name = input("What is your first name?")
print("my name is",f_name)
s_name = input("What is your second name?")
f_num = input ("Enter first number:")
s_num = input("Enter the second number:")
sum_num = int(f_num) + int(s_num)
print("The sum of the numbers is:",sum_num)
#convert the string into integers
sum_num = int(f_num) + int(s_num)
#convert the string into integers
print("The sum of the numbers is:",sum_num)
diff_num = int(f_num) - int(s_num)
print("The difference of the numbers is:",diff_num)
quot_num = int(f_num) / int(s_num)
print("The quotient of the numbers is:",quot_num)
prod_num = int(f_num) / int(s_num)
print("The product of the numbers is:",prod_num)